version: "3.7"

services:

  tagservice:
    image: tagservice:latest
    build:
      context: .
    volumes:
      - ./:/app/
    networks:
      - deployml_network
    depends_on:
      - mymongo
    ports:
      - 8002:8000
    # env_file:
    #   - ./.env

  mymongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-rootpassword}
    volumes:
      - mongodb-data:/data/db
    # ports:
    #   - "27017:27017"
    networks:
      - deployml_network
    restart: always
networks:
  deployml_network:
    driver: bridge

volumes:
  mongodb-data:
    name: "tag-mongo-data"
